# Part of buz addons for Mogen Co. See LICENSE file.
from odoo import _, api, fields, models
from odoo.exceptions import ValidationError
from odoo.tools import float_compare


class MrpUnbuildComponentLine(models.Model):
    """Editable preview of one component returned by an unbuild order.

    Lines are generated by exploding the BOM as soon as product, BOM and
    quantity are set on the unbuild order. The user can then adjust the
    quantity, choose a destination location per component, skip components
    (receive=False) or scrap part of the returned quantity before the
    unbuild order is confirmed.
    """

    _name = 'mrp.unbuild.component.line'
    _description = 'Unbuild Component Line'
    _order = 'sequence, id'

    unbuild_id = fields.Many2one(
        'mrp.unbuild',
        string='Unbuild Order',
        required=True,
        ondelete='cascade',
        index=True,
    )
    sequence = fields.Integer(default=10)
    bom_line_id = fields.Many2one(
        'mrp.bom.line',
        string='BOM Line',
        readonly=True,
        help='Original BOM line this component comes from.',
    )
    product_id = fields.Many2one(
        'product.product',
        string='Component',
        required=True,
        check_company=True,
    )
    product_uom_id = fields.Many2one(
        'uom.uom',
        string='Unit of Measure',
        required=True,
    )
    product_uom_category_id = fields.Many2one(
        related='product_id.uom_id.category_id')
    tracking = fields.Selection(related='product_id.tracking')
    expected_qty = fields.Float(
        string='Expected Qty',
        digits='Product Unit of Measure',
        readonly=True,
        help='Quantity computed from the BOM (BOM line quantity x unbuild '
             'quantity). Kept as reference when the user edits the quantity.',
    )
    quantity = fields.Float(
        string='Quantity',
        digits='Product Unit of Measure',
        required=True,
        help='Total quantity recovered from the unbuild for this component '
             '(including the scrapped part).',
    )
    receive = fields.Boolean(
        string='Receive',
        default=True,
        help='Untick to skip this component entirely: no stock move and no '
             'scrap will be created (e.g. component destroyed or lost).',
    )
    scrap_qty = fields.Float(
        string='Scrap Qty',
        digits='Product Unit of Measure',
        help='Part of the quantity to scrap after reception. Example: '
             'quantity 10 and scrap 2 leaves 8 in the destination location '
             'and 2 in the scrap location.',
    )
    cost_share = fields.Float(
        string='Cost Share (%)',
        digits=(5, 2),
        help='Percentage of the unbuilt product\'s actual consumed value '
             '(real cost, e.g. FIFO layer value) allocated to this '
             'component. Required: the Cost Share of all received '
             'components on the order must add up to 100 before the '
             'unbuild can be confirmed.',
    )
    destination_location_id = fields.Many2one(
        'stock.location',
        string='Destination Location',
        domain="[('usage', '=', 'internal')]",
        check_company=True,
        help='Internal location where this component will be returned.',
    )
    lot_id = fields.Many2one(
        'stock.lot',
        string='Lot/Serial',
        domain="[('product_id', '=', product_id)]",
        check_company=True,
        help='Lot/serial used for the scrap of tracked components. Stock '
             'moves of tracked components take their lots from the linked '
             'Manufacturing Order (standard Odoo behavior).',
    )
    owner_id = fields.Many2one(
        'res.partner',
        string='Owner',
        check_company=True,
    )
    package_id = fields.Many2one(
        'stock.quant.package',
        string='Package',
        check_company=True,
    )
    note = fields.Char(string='Notes')
    company_id = fields.Many2one(
        related='unbuild_id.company_id',
        store=True,
        index=True,
    )
    state = fields.Selection(related='unbuild_id.state')
    is_unbuild_manager = fields.Boolean(
        compute='_compute_is_unbuild_manager',
        help='Technical: current user belongs to the MRP Unbuild Manager '
             'group. Drives edit rights on quantity/location/scrap.',
    )

    def _compute_is_unbuild_manager(self):
        is_manager = self.env.user.has_group(
            'buz_mrp_unbuild_enhancement.group_unbuild_manager')
        for line in self:
            line.is_unbuild_manager = is_manager

    @api.constrains('destination_location_id')
    def _check_destination_location(self):
        for line in self:
            location = line.destination_location_id
            if location and location.usage != 'internal':
                raise ValidationError(_(
                    'Destination location "%(location)s" on component '
                    '"%(product)s" must be an internal location.',
                    location=location.display_name,
                    product=line.product_id.display_name,
                ))

    @api.constrains('scrap_qty', 'quantity')
    def _check_scrap_qty(self):
        for line in self:
            rounding = line.product_uom_id.rounding or 0.01
            if float_compare(line.scrap_qty, 0.0,
                             precision_rounding=rounding) < 0:
                raise ValidationError(_(
                    'Scrap quantity of component "%(product)s" cannot be '
                    'negative.', product=line.product_id.display_name))
            if float_compare(line.scrap_qty, line.quantity,
                             precision_rounding=rounding) > 0:
                raise ValidationError(_(
                    'Scrap quantity (%(scrap)s) of component "%(product)s" '
                    'cannot exceed the returned quantity (%(qty)s).',
                    scrap=line.scrap_qty,
                    product=line.product_id.display_name,
                    qty=line.quantity,
                ))

    @api.constrains('cost_share')
    def _check_cost_share(self):
        for line in self:
            if not (0.0 <= line.cost_share <= 100.0):
                raise ValidationError(_(
                    'Cost Share ของชิ้นส่วน "%(product)s" ต้องอยู่ระหว่าง '
                    '0 ถึง 100', product=line.product_id.display_name))

    @api.onchange('quantity')
    def _onchange_quantity_warning(self):
        """Warn (do not block) when the edited quantity exceeds the
        BOM-computed quantity."""
        for line in self:
            rounding = line.product_uom_id.rounding or 0.01
            if line.expected_qty and float_compare(
                    line.quantity, line.expected_qty,
                    precision_rounding=rounding) > 0:
                return {
                    'warning': {
                        'title': _('Quantity above BOM'),
                        'message': _(
                            'Component "%(product)s": quantity %(qty)s is '
                            'higher than the BOM quantity %(expected)s.',
                            product=line.product_id.display_name,
                            qty=line.quantity,
                            expected=line.expected_qty,
                        ),
                    }
                }
        return None

    @api.onchange('product_id')
    def _onchange_product_id(self):
        for line in self:
            if line.product_id:
                line.product_uom_id = line.product_id.uom_id

    def write(self, vals):
        """Audit trail: log edits of sensitive values on the unbuild chatter."""
        audited = {
            'quantity': _('Quantity'),
            'scrap_qty': _('Scrap Qty'),
            'destination_location_id': _('Destination Location'),
            'cost_share': _('Cost Share (%)'),
        }
        tracked_fields = [f for f in audited if f in vals]
        old_values = {}
        if tracked_fields:
            for line in self:
                old_values[line.id] = {
                    f: line[f] for f in tracked_fields}
        res = super().write(vals)
        if tracked_fields:
            for line in self:
                changes = []
                for field_name in tracked_fields:
                    old = old_values[line.id][field_name]
                    new = line[field_name]
                    if old == new:
                        continue
                    if field_name == 'destination_location_id':
                        old = old.display_name or '-'
                        new = new.display_name or '-'
                    changes.append('%s: %s → %s' % (
                        audited[field_name], old, new))
                if changes and line.unbuild_id:
                    line.unbuild_id.message_post(
                        body=_(
                            'Component "%(product)s" updated: %(changes)s',
                            product=line.product_id.display_name,
                            changes=', '.join(changes),
                        ),
                        subtype_xmlid='mail.mt_note',
                    )
        return res
