# -*- coding: utf-8 -*-
"""
Claims Report XLSX Export

Generates Excel report using xlsxwriter via report_xlsx module.
"""
from odoo import models


class ServiceClaimXlsx(models.AbstractModel):
    """
    Claims Report XLSX Export

    Inherits report.report_xlsx.abstract to generate Excel files
    using xlsxwriter. One row per service.receipt.line, showing
    withdrawn (เบิก - replacement product sent to customer) and
    returned (คืน - original product received from customer) qty,
    dates, and remaining balance.
    """
    _name = 'report.buz_service_receipt.report_service_claim_xlsx'
    _inherit = 'report.report_xlsx.abstract'
    _description = 'Claims Report XLSX'

    def _get_state_label(self, claim):
        state_selection = claim._fields['state'].selection
        return dict(state_selection).get(claim.state, '')

    def _get_done_qty(self, picking, product):
        """Sum of actually done move quantity for a product on a picking.
        Returns 0 if the picking has no product/is not created, or the moves
        for that product haven't been validated (state != 'done') yet —
        planned/reserved qty on an unfinished picking does NOT count."""
        if not picking or not product:
            return 0.0
        done_moves = picking.move_ids.filtered(
            lambda m: m.product_id == product and m.state == 'done'
        )
        return sum(done_moves.mapped('quantity'))

    def generate_xlsx_report(self, workbook, data, claims):
        sheet = workbook.add_worksheet('Claims')

        bold = workbook.add_format({'bold': True})
        title = workbook.add_format({
            'bold': True,
            'align': 'center',
            'bg_color': '#4F81BD',
            'font_color': 'white',
            'border': True,
            'font_size': 14,
        })
        header = workbook.add_format({
            'bold': True,
            'bg_color': '#D3E4F8',
            'align': 'center',
            'border': True,
            'text_wrap': True,
        })
        number = workbook.add_format({'num_format': '#,##0.00'})
        date_format = workbook.add_format({'num_format': 'dd/mm/yyyy'})

        headers = [
            'เลขที่ใบขอ', 'เลขที่ใบแจ้ง', 'ลูกค้า',
            'วันที่เบิก', 'เลขที่เอกสารเบิก', 'สินค้า (เบิก)', 'จำนวน (เบิก)',
            'วันที่คืน', 'เลขที่เอกสารคืน', 'สินค้า (คืน)', 'จำนวน (คืน)',
            'คงเหลือ', 'ผู้ทำรายการ', 'สถานะ',
        ]
        widths = [16, 16, 24, 14, 18, 28, 12, 14, 18, 28, 12, 12, 20, 16]
        for col, width in enumerate(widths):
            sheet.set_column(col, col, width)

        row = 0
        sheet.merge_range(row, 0, row, len(headers) - 1, 'Claims Report', title)
        row += 2
        sheet.write(row, 0, 'Report Date:', bold)
        sheet.write(row, 1, self.env.context.get('report_date', ''))
        sheet.write(row, 3, 'Generated by:', bold)
        sheet.write(row, 4, self.env.user.name)
        row += 2

        for col, header_text in enumerate(headers):
            sheet.write(row, col, header_text, header)
        sheet.freeze_panes(row + 1, 0)
        row += 1

        for claim in claims:
            withdraw_date = claim.replacement_picking_id.date_done or claim.service_date
            return_date = claim.return_picking_id.date_done or claim.service_date
            requester = claim.create_uid.name or ''

            for line in claim.line_ids:
                # Remaining is based on actually validated (done) move qty, not the
                # planned qty on the line — it only reaches 0 once both the withdraw
                # and return pickings have been done with matching quantities.
                done_withdraw_qty = self._get_done_qty(claim.replacement_picking_id, line.replacement_product_id)
                done_return_qty = self._get_done_qty(claim.return_picking_id, line.product_id)
                remaining = done_withdraw_qty - done_return_qty

                sheet.write(row, 0, claim.claim_number or '')
                sheet.write(row, 1, claim.name or '')
                sheet.write(row, 2, claim.partner_id.name or '')
                if withdraw_date:
                    sheet.write(row, 3, withdraw_date, date_format)
                else:
                    sheet.write(row, 3, '')
                sheet.write(row, 4, claim.replacement_picking_id.name or '')
                sheet.write(row, 5, line.replacement_product_id.display_name or '')
                sheet.write(row, 6, line.replacement_qty or 0.0, number)
                if return_date:
                    sheet.write(row, 7, return_date, date_format)
                else:
                    sheet.write(row, 7, '')
                sheet.write(row, 8, claim.return_picking_id.name or '')
                sheet.write(row, 9, line.product_id.display_name or '')
                sheet.write(row, 10, line.quantity or 0.0, number)
                sheet.write(row, 11, remaining, number)
                sheet.write(row, 12, requester)
                sheet.write(row, 13, self._get_state_label(claim))
                row += 1
