{
    'name': 'IT Asset',
    'version': '17.0.1.16.0',
    'category': 'Services/IT',
    'summary': 'Hardware and software asset registry for IT Management',
    'author': 'BUZ',
    'license': 'LGPL-3',
    'depends': ['buz_it_helpdesk', 'hr', 'mail'],
    'data': [
        'data/hardware_taxonomy.xml',
        'data/software_types.xml',
        'data/repair_outcomes.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/asset_views.xml',
        'views/ticket_repair_views.xml',
        'views/repair_outcome_views.xml',
        'views/software_views.xml',
        'views/dashboard_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'buz_it_asset/static/src/js/it_management_dashboard.js',
            'buz_it_asset/static/src/xml/it_management_dashboard.xml',
            'buz_it_asset/static/src/scss/it_management_dashboard.scss',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
}
