# -*- coding: utf-8 -*-
"""
Payment Voucher Report XLSX Export

Generates Excel report using xlsxwriter via report_xlsx module.
"""
from odoo import models
from datetime import datetime


class PaymentVoucherXlsx(models.AbstractModel):
    """
    Payment Voucher Report XLSX Export

    Inherits report.report_xlsx.abstract to generate Excel files
    using xlsxwriter.

    Supports multi-payment export in one consolidated worksheet.
    """
    _name = 'report.buz_payment_voucher_report.report_payment_voucher_xlsx'
    _inherit = 'report.report_xlsx.abstract'
    _description = 'Payment Voucher Report XLSX'

    def _get_payment_type_label(self, payment):
        payment_type_selection = payment._fields['payment_type'].selection
        return dict(payment_type_selection).get(payment.payment_type, '')

    def _get_reconciled_document_names(self, payment):
        return payment._get_reconciled_invoice_names()

    def generate_xlsx_report(self, workbook, data, payments):
        """
        Generate XLSX report for selected payments.

        Creates one worksheet containing all journal items for all selected
        payments, with a subtotal row per payment and a grand total row.

        :param workbook: xlsxwriter Workbook object
        :param data: dict with report data (from wizard)
        :param payments: account.payment recordset
        """
        sheet = workbook.add_worksheet('Payment Voucher')

        bold = workbook.add_format({'bold': True})
        title = workbook.add_format({
            'bold': True,
            'align': 'center',
            'bg_color': '#4F81BD',
            'font_color': 'white',
            'border': True,
            'font_size': 14,
        })
        header = workbook.add_format({
            'bold': True,
            'bg_color': '#D3E4F8',
            'align': 'center',
            'border': True,
            'text_wrap': True,
        })
        subtotal = workbook.add_format({
            'bold': True,
            'bg_color': '#F3F6FA',
            'border': True,
            'num_format': '#,##0.00',
        })
        grand_total = workbook.add_format({
            'bold': True,
            'bg_color': '#D9EAD3',
            'border': True,
            'num_format': '#,##0.00',
        })
        number = workbook.add_format({'num_format': '#,##0.00'})
        date_format = workbook.add_format({'num_format': 'dd/mm/yyyy'})

        widths = [
            18, 12, 18, 26, 20, 16, 18, 30, 14, 28, 14, 16, 24, 10, 14, 30,
        ]
        for col, width in enumerate(widths):
            sheet.set_column(col, col, width)

        headers = [
            'Payment Number', 'Payment Date', 'Partner Code', 'Partner',
            'Journal', 'Payment Type', 'Payment Method', 'Label',
            'Account Code', 'Account Name', 'Debit', 'Credit',
            'Amount Currency', 'Reference', 'Currency',
            'Reconciled Documents',
        ]

        row = 0
        sheet.merge_range(row, 0, row, len(headers) - 1, 'Payment Voucher', title)
        row += 2
        sheet.write(row, 0, 'Report Date:', bold)
        sheet.write(row, 1, datetime.now(), date_format)
        sheet.write(row, 3, 'Generated by:', bold)
        sheet.write(row, 4, self.env.user.name)
        row += 2

        for col, header_text in enumerate(headers):
            sheet.write(row, col, header_text, header)
        sheet.freeze_panes(row + 1, 0)
        row += 1

        grand_debit = 0.0
        grand_credit = 0.0

        for payment in payments:
            payment_debit = 0.0
            payment_credit = 0.0
            payment_type_label = self._get_payment_type_label(payment)
            reconciled_names = self._get_reconciled_document_names(payment)

            for line in payment.move_id.line_ids:
                sheet.write(row, 0, payment.name or '')
                sheet.write(row, 1, payment.date or '', date_format)
                sheet.write(row, 2, payment.partner_id.partner_code if payment.partner_id else '')
                sheet.write(row, 3, payment.partner_id.name if payment.partner_id else '')
                sheet.write(row, 4, payment.journal_id.name if payment.journal_id else '')
                sheet.write(row, 5, payment_type_label)
                payment_method = payment.payment_method_id.name if payment.payment_method_id else ''
                sheet.write(row, 6, payment_method)
                sheet.write(row, 7, line.name or '')
                sheet.write(row, 8, line.account_id.code or '')
                sheet.write(row, 9, line.account_id.name or '')
                sheet.write(row, 10, line.debit or 0.0, number)
                sheet.write(row, 11, line.credit or 0.0, number)
                sheet.write(row, 12, line.amount_currency or 0.0, number)
                sheet.write(row, 13, payment.payment_reference or '')
                sheet.write(row, 14, line.currency_id.name or payment.currency_id.name or '')
                sheet.write(row, 15, reconciled_names)

                payment_debit += line.debit or 0.0
                payment_credit += line.credit or 0.0
                row += 1

            sheet.write(row, 0, 'Subtotal', subtotal)
            sheet.write(row, 1, payment.name or '', subtotal)
            sheet.write(row, 10, payment_debit, subtotal)
            sheet.write(row, 11, payment_credit, subtotal)
            difference = payment_debit - payment_credit
            balance_status = (
                'UNBALANCED %.2f' % difference
                if abs(difference) > 0.01 else 'Balanced'
            )
            sheet.write(row, 13, balance_status, subtotal)
            row += 1

            grand_debit += payment_debit
            grand_credit += payment_credit

        sheet.write(row, 0, 'Grand Total', grand_total)
        sheet.write(row, 10, grand_debit, grand_total)
        sheet.write(row, 11, grand_credit, grand_total)
        difference = grand_debit - grand_credit
        balance_status = (
            'UNBALANCED %.2f' % difference
            if abs(difference) > 0.01 else 'Balanced'
        )
        sheet.write(row, 13, balance_status, grand_total)
