from . import product_template
from . import product
from . import product_category
from . import res_partner
from . import warranty_card
from . import warranty_dashboard
from . import warranty_dashboard_cache
from . import stock_picking
from . import sale_order
from . import res_config_settings
